name: Test

on:
  push:
    branches:
      - test-the-pr
  schedule:
    # Run at 03:00 UTC daily
    - cron: "0 3 * * *"

env:
  REGISTRY: ghcr.io
  PACKAGE: github.com/${{ github.repository }}
  ORG: ${{ github.repository_owner }}
  PROJECT: ${ github.event.repository.name }
  IMAGE_REGISTRY_PATH: ${{ github.repository }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}

jobs:
  normal_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run normal CI
        run: echo "Running normal CI"

  pull_request_ci:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Run PR CI
        run: |
            echo "Running PR CI"
            echo "Package: ${{ env.PACKAGE }}"
            echo "Org: ${{ env.ORG }}"
            echo "Project: ${{ env.PROJECT }}"
            echo "Image Registry Path: ${{ env.IMAGE_REGISTRY_PATH }}"
            echo "Image Registry User: ${{ env.IMAGE_REGISTRY_USER }}"